N_("")
N_("Allow folding of C style comments")
N_("Allow folding of Curly brackets block")
N_("Allow folding of Javascript Curly brackets block")
N_("Allow folding of Javascript Parentheses block")
N_("Allow folding of Javascript Square brackets block")
N_("Allow folding of Parentheses block")
N_("Allow folding of PHP blocks")
N_("Allow folding of Square brackets block")
N_("Allow folding of the Parentheses block")
N_("Allow to fold the the root html tag")
N_("All php functions")
N_("All wordpress functions")
N_("Autocomplete function names with semicolon")
N_("Autocomplete HTML entities")
N_("Autocomplete Javascript object methods")
N_("autocomplete javascript variables")
N_("Auto-complete PHP functions")
N_("Auto-complete PHP variables")
N_("Autocomplete tags")
N_("autocomplete with newlines")
N_("CSS properties")
N_("Enable the PHP short open tag")
N_("GNU Coreutils functions")
N_("HTML entities")
N_("include JQuery syntax")
N_("Javascript CSS properties")
N_("Load all php functions")
N_("Load auto-completion information")
N_("Load completion data")
N_("Load glib types and functions")
N_("Load GObject functions")
N_("Load GTK+ functions")
N_("Load reference data")
N_("Load reference information")
N_("Load standard C library functions ")
N_("Load XSLT 2.0 support.")
N_("Methods in javadoc but not in references")
N_("scan for sql in php strings")
N_("Scan for sql in strings")
N_("Self-close tags such as br, hr, and img with /&gt;")
N_("Show a string as a block")
N_("Show tag attributes as block")
N_("Show this language in the menu")
N_("Tag block-start includes all attributes")
